version: "3.9"
networks:
  cover_craft_network:
    name: cover_craft_network
    driver: bridge
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      db:
          condition: service_healthy
    env_file:
      - .env
    networks:
      - cover_craft_network
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - cover_craft_network
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5